/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.82
 * Generated at: 2022-09-21 07:02:08 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.member;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import kr.co.ansany.member.model.vo.Member;

public final class myPage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/views/common/header.jsp", Long.valueOf(1663743489218L));
    _jspx_dependants.put("/WEB-INF/views/common/footer.jsp", Long.valueOf(1663743044693L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("kr.co.ansany.member.model.vo.Member");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<title>마이페이지</title>\n");
      out.write("    <!--css-->\n");
      out.write("    <link rel=\"stylesheet\" href=\"/css/myPage.css\">\n");
      out.write("    <!--fonts-->\n");
      out.write("    <link rel=\"stylesheet\" href=\"/css/Noto_Sans.css\">\n");
      out.write("    <!--jquery-->\n");
      out.write("    <script src=\"https://code.jquery.com/jquery-3.6.0.js\"></script>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("\n");
      out.write("    ");

    	Member m = (Member)session.getAttribute("m");
    
      out.write("\n");
      out.write("    <!--css-->\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/header.css\">\n");
      out.write("    <!--fonts-->\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/Noto_Sans.css\">\n");
      out.write("    <!--구글 아이콘-->\n");
      out.write("    <link href=\"https://fonts.googleapis.com/icon?family=Material+Icons\" rel=\"stylesheet\">\n");
      out.write("    <!--jquery-->\n");
      out.write("    <script src=\"https://code.jquery.com/jquery-3.6.0.js\"></script>\n");
      out.write("    <div class=\"header-body\">\n");
      out.write("        <div class=\"header-fixed\">\n");
      out.write("            <div class=\"header-wrap\">\n");
      out.write("                <div class=\"header-top\">\n");
      out.write("                    <div class=\"header-logo\"><a href=\"/\"><img src=\"img/logo2.png\" alt=\"\"></a></div>\n");
      out.write("                    <div class=\"header-navi\">\n");
      out.write("                        <ul>\n");
      out.write("                            <li>\n");
      out.write("                                <a href=\"#\">제품</a>\n");
      out.write("                                <ul>\n");
      out.write("                                    <li><a href=\"#\">헤드폰/이어폰</a></li>\n");
      out.write("                                    <li><a href=\"#\">스피커</a></li>\n");
      out.write("                                    <li><a href=\"#\">턴테이블</a></li>\n");
      out.write("                                    <li><a href=\"#\">워크맨</a></li>\n");
      out.write("                                </ul>\n");
      out.write("                            </li>\n");
      out.write("                            <li>\n");
      out.write("                                <a href=\"#\">커뮤니티</a>\n");
      out.write("                                <ul>\n");
      out.write("                                    <li><a href=\"#\">공지사항</a></li>\n");
      out.write("                                    <li><a href=\"#\">구매후기</a></li>\n");
      out.write("                                    <li><a href=\"#\">사진전</a></li>\n");
      out.write("                                    <li><a href=\"#\">자유게시판</a></li>\n");
      out.write("                                </ul>\n");
      out.write("                            </li>\n");
      out.write("                            <li><a href=\"#\">멤버십</a>\n");
      out.write("                                <ul>\n");
      out.write("                                    <li><a href=\"#\">등급&혜택 안내</a></li>\n");
      out.write("                                </ul>\n");
      out.write("                            </li>\n");
      out.write("                            <li>\n");
      out.write("                                <a href=\"#\">고객 서비스</a>\n");
      out.write("                                <ul>\n");
      out.write("                                    <li><a href=\"#\">FAQ / Q<span>&</span>A</a></li>\n");
      out.write("                                    <li><a href=\"#\"></a></li>\n");
      out.write("                                </ul>\n");
      out.write("                            </li>\n");
      out.write("                            <li>\n");
      out.write("                                <a href=\"#\">직영점 안내</a>\n");
      out.write("                                <ul>\n");
      out.write("                                    <li><a href=\"#\">찾아오시는길</a></li>\n");
      out.write("                                </ul>\n");
      out.write("                            </li>\n");
      out.write("                        </ul>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"header-icon\">\n");
      out.write("                        <div class=\"icon-wrap\">\n");
      out.write("                            <div>\n");
      out.write("                                <a href=\"#\">\n");
      out.write("                                    <span class=\"material-icons\">shopping_cart</span>\n");
      out.write("                                </a>\n");
      out.write("                            </div>\n");
      out.write("                            <div>\n");
      out.write("                                ");
if(m==null) {
      out.write("\n");
      out.write("                                <a href=\"/loginFrm.do\">\n");
      out.write("                                    <span class=\"material-icons\">person</span>\n");
      out.write("                                </a>\n");
      out.write("                                ");
}else{ 
      out.write("\n");
      out.write("                                ");
if(m.getMemberLevel()==1) {
      out.write("\n");
      out.write("                                <a href=\"/adminPage.do\">\n");
      out.write("                                	<span class=\"material-icons\" style=\"color:#5865f5\">person</span>\n");
      out.write("                                </a>\n");
      out.write("                                ");
} else{ 
      out.write("\n");
      out.write("                                <a href=\"/myPageFrm.do\">\n");
      out.write("                                    <span class=\"material-icons\" style=\"color:#5865f5\">person</span>\n");
      out.write("                                </a>\n");
      out.write("                                ");
} 
      out.write("\n");
      out.write("                                ");
} 
      out.write("\n");
      out.write("                            </div>\n");
      out.write("                            <div>\n");
      out.write("                                <a href=\"#\">\n");
      out.write("                                    <span class=\"material-icons\">search</span>\n");
      out.write("                                </a>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div><!--헤더 끝-->\n");
      out.write("    <!-- js -->\n");
      out.write("    <script src=\"/js/header.js\"></script>");
      out.write("\n");
      out.write("<content>\n");
      out.write("        <div class=\"mypage-wrap\">\n");
      out.write("            <div class=\"mypage-header\">\n");
      out.write("                <h1>마이페이지</h1>\n");
      out.write("                <div class=\"span-wrap\">\n");
      out.write("                    <span class=\"welecome\">회원이름 안녕하세요 :)</span>\n");
      out.write("                    <a href=\"/logout.do\" class=\"logoutLink\" name=\"logout\">로그아웃</a>\n");
      out.write("                </div>\n");
      out.write("                <ul class=\"header-box\">\n");
      out.write("                    <a href=\"#\"><li class=\"oneMemberLevel\">회원등급</li></a>\n");
      out.write("                    <a href=\"#\"><li class=\"oneMemberInfo\">회원정보수정</li></a>\n");
      out.write("                    <a href=\"#\"><li class=\"oneMembercart\">장바구니</li></a>\n");
      out.write("                </ul>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"mypage-content\">\n");
      out.write("                <div class=\"memberOrder_tbl\">\n");
      out.write("                    <h1>주문내역</h1>\n");
      out.write("                    <table>\n");
      out.write("                        <colgroup>\n");
      out.write("                            <col style=\"width: 120px;\">\n");
      out.write("                            <col>\n");
      out.write("                            <col style=\"width: 160px;\">\n");
      out.write("                            <col style=\"width: 160px;\">\n");
      out.write("                        </colgroup>\n");
      out.write("                        <tread>\n");
      out.write("                            <tr>\n");
      out.write("                                <th scope=\"col\">주문일</th>\n");
      out.write("                                <th scope=\"col\">주문번호</th>\n");
      out.write("                                <th scope=\"col\">상품정보</th>\n");
      out.write("                                <th scope=\"col\">상품가격</th>\n");
      out.write("                            </tr>\n");
      out.write("                        </tread>\n");
      out.write("                        <tbody>\n");
      out.write("                            <tr>\n");
      out.write("                                <td scope=\"col\">주문날짜</td>\n");
      out.write("                                <td scope=\"col\">주문번호</td>\n");
      out.write("                                <td scope=\"col\">상품명</td>\n");
      out.write("                                <td scope=\"col\">내용</td>\n");
      out.write("                            </tr>\n");
      out.write("                        </tbody>\n");
      out.write("                    </table>\n");
      out.write("                    <p>\n");
      out.write("                        작성 가능한 구매후기가 있어요 구매후기를 작성하신 고객님께\n");
      out.write("                        <strong class=\"reserve\">적립금</strong>\n");
      out.write("                        을 지급해 드립니다\n");
      out.write("                    </p>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"myBoardView_tbl\">\n");
      out.write("                    <h1>1:1 문의내역</h1>\n");
      out.write("                    <table>\n");
      out.write("                        <colgroup>\n");
      out.write("                            <col style=\"width: 120px;\">\n");
      out.write("                            <col>\n");
      out.write("                            <col style=\"width: 160px;\">\n");
      out.write("                            <col style=\"width: 160px;\">\n");
      out.write("                            <col style=\"width: 100px;\">\n");
      out.write("                        </colgroup>\n");
      out.write("                        <tread>\n");
      out.write("                            <tr>\n");
      out.write("                                <th scope=\"col\">상담구분</th>\n");
      out.write("                                <th scope=\"col\">상담제목</th>\n");
      out.write("                                <th scope=\"col\">작성일</th>\n");
      out.write("                                <th scope=\"col\">답변유무</th>\n");
      out.write("                                <th scope=\"col\">삭제</th>\n");
      out.write("                            </tr>\n");
      out.write("                        </tread>\n");
      out.write("                        <tbody>\n");
      out.write("                            <tr>\n");
      out.write("                                <td>교환문의</td>\n");
      out.write("                                <td>색상변경</td>\n");
      out.write("                                <td>작성일</td>\n");
      out.write("                                <td>답변유무</td>\n");
      out.write("                                <td class=\"colDelete-btn\">\n");
      out.write("                                    <button type=\"button\">삭제</button>\n");
      out.write("                                </td>\n");
      out.write("                            </tr>\n");
      out.write("                        </tbody>\n");
      out.write("                    </table><!--table 끝-->\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </content><!--컨텐츠 끝-->\n");
      out.write("\n");
      out.write("<link rel=\"stylesheet\" href=\"/css/footer.css\" />\n");
      out.write("<footer>\n");
      out.write("	<div class=\"footer-content\">\n");
      out.write("		<div class=\"footer-left\">\n");
      out.write("			<div class=\"footer-link\">\n");
      out.write("				<ul>\n");
      out.write("					<li><a href=\"#\">이용약관</a></li>\n");
      out.write("					<li><a href=\"#\">개인정보처리방침</a></li>\n");
      out.write("					<li><a href=\"#\">소비자 피해 보상보험</a></li>\n");
      out.write("					<li><a href=\"#\">사이트 맵</a></li>\n");
      out.write("				</ul>\n");
      out.write("			</div>\n");
      out.write("			<p class=\"small-size\">* 본 사이트의 컨텐츠는 저작권법의 보호를 받는 바, 상업적 목적의 무단전재,\n");
      out.write("				복사, 배포 등을 금합니다.</p>\n");
      out.write("			<p class=\"small-size\">* 소비자피해보상보험 고객님은 안전거래를 위해 현금 등으로 결제 시 저희\n");
      out.write("				쇼핑몰에서 가입한 구매안전서비스를 이용하실 수 있습니다.</p>\n");
      out.write("			<p class=\"bold-size\">사업장 주소: 서울특별시 영등포구 선유동2로 57 이레빌딩 19층 A강의실</p>\n");
      out.write("			<p class=\"bold-size\">개인정보관리책임자: AnSany TEL: 안사니 고객센터 1588-4444\n");
      out.write("				EMAIL: ansany_contact@ansany.com</p>\n");
      out.write("			<p class=\"bold-size\">Copyright © An Sany Corporation. All rights\n");
      out.write("				reserved.</p>\n");
      out.write("		</div>\n");
      out.write("		<div class=\"footer-right\">\n");
      out.write("			<div class=\"followus\">FOLLOW US</div>\n");
      out.write("			<div class=\"site-logos\">\n");
      out.write("				<a href=\"https://www.facebook.com/sonykorea\" target=\"_blank\"><img\n");
      out.write("					src=\"/img/facebook.png\" class=\"logos\"></a> <a\n");
      out.write("					href=\"https://www.instagram.com/sonykorea/\" target=\"_blank\"><img\n");
      out.write("					src=\"/img/instagram.png\" class=\"logos\"></a> <a\n");
      out.write("					href=\"https://www.youtube.com/user/sonystyleblog\" target=\"_blank\"><img\n");
      out.write("					src=\"/img/youtube.png\" class=\"logos\"></a> <a\n");
      out.write("					href=\"https://stylezineblog.com/?intcmp=Main_Blog\" target=\"_blank\"><img\n");
      out.write("					src=\"/img/blog.png\" class=\"logos\"></a>\n");
      out.write("			</div>\n");
      out.write("		</div>\n");
      out.write("	</div>\n");
      out.write("</footer>");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
